name: PIS server

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@master
    - name: Publish to Registry
      uses: elgohr/Publish-Docker-Github-Action@master
      with:
        name: pis-ideaserv/server
        username: ${{ secrets.USERNAME }}
        password: ${{ secrets.PASSWORD }}
        registry: docker.pkg.github.com
        tag_names: true
